курсовая

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split

## подготовка данных

In [4]:
revs = pd.read_csv('/Users/m.makarov/Documents/мирэа тетрал/курсач/IMDB Dataset.csv')

revs_train, revs_test = train_test_split(
    revs,
    test_size=0.2,
    random_state=42,
    stratify=revs['sentiment']
)
revs_train

                                                  review sentiment
47808  I caught this little gem totally by accident b...  positive
20154  I can't believe that I let myself into this mo...  negative
43069  *spoiler alert!* it just gets to me the nerve ...  negative
19413  If there's one thing I've learnt from watching...  negative
13673  I remember when this was in theaters, reviews ...  negative
...                                                  ...       ...
31092  It's the 1920s. And a man named Walt Disney wa...  positive
22917  The first (and only) time I saw "Shades" was d...  negative
47481  This was such a waste of time. Danger: If you ...  negative
35597  this is by far the most pathetic movie Indian ...  negative
27491  This movie forever left an impression on me. I...  negative

[40000 rows x 2 columns]

In [5]:
revs['p/n'] = revs['sentiment'].map({'positive': 1, 'negative': 0})     #новый столбец: 1 - позитивый, 2 - негативный
revs

                                                  review sentiment  p/n
0      One of the other reviewers has mentioned that ...  positive    1
1      A wonderful little production. <br /><br />The...  positive    1
2      I thought this was a wonderful way to spend ti...  positive    1
3      Basically there's a family where a little boy ...  negative    0
4      Petter Mattei's "Love in the Time of Money" is...  positive    1
...                                                  ...       ...  ...
49995  I thought this movie did a down right good job...  positive    1
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative    0
49997  I am a Catholic taught in parochial elementary...  negative    0
49998  I'm going to have to disagree with the previou...  negative    0
49999  No one expects the Star Trek movies to be high...  negative    0

[50000 rows x 3 columns]

In [18]:
revs_train, revs_test = train_test_split(
    revs,
    test_size=0.5,
    random_state=42,
    stratify=revs['sentiment']
)
revs_train

                                                  review sentiment  p/n
3055   Trio's vignettes were insightful and quite enj...  positive    1
47326  I had never heard of this one before the owner...  negative    0
48869  This is an excellent but hard to find trippy W...  positive    1
48623  I am a huge fan of big, loud, trashy, complete...  positive    1
39657  Easily Lucio Fulci's most respected film, "Don...  positive    1
...                                                  ...       ...  ...
21552  Recent years have seen a number of biopics of ...  positive    1
10610  You may say to yourself, "Don Johnson as Elvis...  negative    0
20104  The title refers not to a questionable poker h...  positive    1
35597  this is by far the most pathetic movie Indian ...  negative    0
27491  This movie forever left an impression on me. I...  negative    0

[25000 rows x 3 columns]

## модель наивного байеса

In [19]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [20]:
model1 = make_pipeline(CountVectorizer(), MultinomialNB())

model1.fit(revs_train['review'], revs_train['p/n'])

Pipeline(steps=[('countvectorizer', CountVectorizer()),
                ('multinomialnb', MultinomialNB())])

In [21]:
y_true = revs_test['p/n']
y_true

16346    0
42137    0
21867    1
12577    0
25444    0
        ..
32628    0
8352     0
49159    1
38453    0
47518    0
Name: p/n, Length: 25000, dtype: int64

In [24]:
y_pred1 = model1.predict(revs_test['review'])
y_pred1

array([0, 0, 0, ..., 0, 0, 0], shape=(25000,))

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score


print('Accuracy: ', accuracy_score(y_true, y_pred1))
print(classification_report(y_true, y_pred1))
print(confusion_matrix(y_true, y_pred1))

Accuracy:  0.8434
f1 score:  0.8387096774193549
              precision    recall  f1-score   support

           0       0.82      0.87      0.85     12500
           1       0.86      0.81      0.84     12500

    accuracy                           0.84     25000
   macro avg       0.84      0.84      0.84     25000
weighted avg       0.84      0.84      0.84     25000

[[10906  1594]
 [ 2321 10179]]

## logistic regression

In [33]:
from sklearn.linear_model import LogisticRegression

model2 = make_pipeline(TfidfVectorizer(), LogisticRegression())

model2.fit(revs_train['review'], revs_train['p/n'])

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('logisticregression', LogisticRegression())])

In [ ]:
y_pred2 = model2.predict(revs_test['review'])
y_true = revs_test['p/n']

print('accuracy: ', accuracy_score(y_true, y_pred2))
print(classification_report(y_true, y_pred2))
print(confusion_matrix(y_true, y_pred2))

accuracy:  0.88968
              precision    recall  f1-score   support

           0       0.90      0.88      0.89     12500
           1       0.88      0.90      0.89     12500

    accuracy                           0.89     25000
   macro avg       0.89      0.89      0.89     25000
weighted avg       0.89      0.89      0.89     25000

[[10976  1524]
 [ 1234 11266]]

## lirear support vector classification

In [39]:
from sklearn.svm import LinearSVC

model3 = make_pipeline(CountVectorizer(), LinearSVC())
model3.fit(revs_train['review'], revs_train['p/n'])

/opt/anaconda3/lib/python3.13/site-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

Pipeline(steps=[('countvectorizer', CountVectorizer()),
                ('linearsvc', LinearSVC())])

In [40]:
y_pred3 = model3.predict(revs_test['review'])
y_true = revs_test['p/n']

print('accuracy: ', accuracy_score(y_true, y_pred3))
print(classification_report(y_true, y_pred3))
print(confusion_matrix(y_true, y_pred3))

accuracy:  0.86552
              precision    recall  f1-score   support

           0       0.87      0.86      0.87     12500
           1       0.86      0.87      0.87     12500

    accuracy                           0.87     25000
   macro avg       0.87      0.87      0.87     25000
weighted avg       0.87      0.87      0.87     25000

[[10792  1708]
 [ 1654 10846]]